# Bag Of Words

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

train_data = [
    "I love programming in Python",
    "i love coding in Java",
    "Python and Java are popular programming languages"
]

vectorizer = CountVectorizer()
vectors = vectorizer.fit_transform(train_data)

print(vectorizer.get_feature_names_out())
print(vectors.toarray())

['and' 'are' 'coding' 'in' 'java' 'languages' 'love' 'popular'
 'programming' 'python']
[[0 0 0 1 0 0 1 0 1 1]
 [0 0 1 1 1 0 1 0 0 0]
 [1 1 0 0 1 1 0 1 1 1]]


In [2]:
from sklearn.feature_extraction.text import CountVectorizer

train_data = [
    "I love programming in Python python",
    "i love coding in Java",
    "Python and Java are popular programming languages",
    "HOML is a great programming book",
]

vectorizer = CountVectorizer()
vectors = vectorizer.fit_transform(train_data)

print(vectorizer.get_feature_names_out())
print(vectors.toarray())

['and' 'are' 'book' 'coding' 'great' 'homl' 'in' 'is' 'java' 'languages'
 'love' 'popular' 'programming' 'python']
[[0 0 0 0 0 0 1 0 0 0 1 0 1 2]
 [0 0 0 1 0 0 1 0 1 0 1 0 0 0]
 [1 1 0 0 0 0 0 0 1 1 0 1 1 1]
 [0 0 1 0 1 1 0 1 0 0 0 0 1 0]]


In [3]:
class category:
    PROGRAMMING = "PROGRAMMING"
    BOOK = "BOOK"

train_y = [
    category.PROGRAMMING,
    category.PROGRAMMING,
    category.BOOK,
    category.BOOK]

In [4]:
from sklearn import svm

clf = svm.SVC()
clf.fit(vectors, train_y)

,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [5]:
test_x = vectorizer.transform([
    "I enjoy writing code in Python"])

clf.predict(test_x)

array(['PROGRAMMING'], dtype='<U11')

In [6]:
test_x = vectorizer.transform(["HOML is a great programming book"])

clf.predict(test_x)

array(['BOOK'], dtype='<U11')

## Bigrams

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

train_data = [
    "I love programming in Python python",
    "i love coding in Java",
    "Python and Java have some great books",
    "HOML is a great programming book",
]

vectorizer = CountVectorizer(binary=True, ngram_range=(1,2))
vectors = vectorizer.fit_transform(train_data)

print(vectorizer.get_feature_names_out())
print(vectors.toarray())

['and' 'and java' 'book' 'books' 'coding' 'coding in' 'great'
 'great books' 'great programming' 'have' 'have some' 'homl' 'homl is'
 'in' 'in java' 'in python' 'is' 'is great' 'java' 'java have' 'love'
 'love coding' 'love programming' 'programming' 'programming book'
 'programming in' 'python' 'python and' 'python python' 'some'
 'some great']
[[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 0 1 1 0 1 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1]
 [0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0]]


# Word Vectors

In [8]:
import spacy

nlp = spacy.load("en_core_web_md")


c:\Users\iamha\miniconda3\envs\fastai\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
c:\Users\iamha\miniconda3\envs\fastai\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(


In [9]:
docs = [nlp(text) for text in train_data]
print(docs)

[I love programming in Python python, i love coding in Java, Python and Java have some great books, HOML is a great programming book]


In [10]:
docs = [nlp(text) for text in train_data]
print(docs[0].vector)

[-6.63409948e-01 -1.95676669e-01 -5.47209941e-02 -2.61027981e-02
  1.20574854e-01  1.60077333e-01  1.81930006e-01 -3.39810014e-01
  3.64033490e-01  9.19804990e-01 -1.77026495e-01 -3.94433171e-01
  1.64190993e-01  2.09691510e-01 -8.61720741e-03 -8.93743336e-02
 -2.77038336e-01  1.36723244e+00 -3.48758340e-01 -1.71808317e-01
  1.15236320e-01 -1.23884656e-01  8.75129998e-02  1.32950051e-02
 -1.25159174e-01 -9.88301635e-02 -1.34186670e-01 -9.94407833e-02
  4.75226671e-01 -1.11973338e-01 -1.29811168e-01  4.08583470e-02
 -6.56435117e-02 -1.67441685e-02 -1.30218506e-01  1.50151506e-01
 -3.05743486e-01  2.20679164e-01 -3.42896670e-01  5.35226502e-02
 -2.44367823e-01  3.82696800e-02 -1.49044827e-01  1.46821678e-01
 -9.74199995e-02  1.58198670e-01  1.25916637e-02  6.84383437e-02
 -4.57109921e-02 -6.21983372e-02 -1.27316341e-01 -1.29775004e-02
  1.65613275e-02 -1.87398151e-01 -1.26713350e-01 -1.03562497e-01
 -1.57142326e-01 -4.16011661e-01 -1.32330671e-01 -1.33220002e-01
 -3.30007166e-01 -2.65191

In [11]:
clf_svm = svm.SVC()
clf_svm.fit([doc.vector for doc in docs], train_y)

,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [12]:
clf_svm.predict([nlp("Computing").vector])

array(['PROGRAMMING'], dtype='<U11')

# Regex

In [13]:
import re 

regexp = re.compile(r"^ab[^\s]*cd$")
phrases = ["abxcd", "xxx", "zz xabcdx zz", "ab cd"]

matches = []
for phrase in phrases:
    if re.match(regexp, phrase):
        matches.append(phrase)
print(matches)  

['abxcd']


In [14]:
import re 

regexp = re.compile(r"ab[^\s]*cd")
phrases = ["abxcd", "xxx", "zz abxxcd zz", "ab cd"]

matches = []
for phrase in phrases:
    if re.search(regexp, phrase):
        matches.append(phrase)
print(matches)  

['abxcd', 'zz abxxcd zz']


In [15]:
import re

regexp = re.compile(r"bread|story|book")
phrases = ["bread", "story", "book", "bread book"]

matches = []
for phrase in phrases:
    if re.search(regexp, phrase):
        matches.append(phrase)
print(matches)

['bread', 'story', 'book', 'bread book']


In [16]:
import re

regexp = re.compile(r"\bbread\b|\bstory\b|\bbook\b")
phrases = ["breaded", "history", "booked", "bread book"]

matches = []
for phrase in phrases:
    if re.search(regexp, phrase):
        matches.append(phrase)
print(matches)

['bread book']


# Stemming/Lemmatization

In [17]:
import nltk

nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\iamha\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\iamha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\iamha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [18]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

phrase = "reading readers readily read readable readings"
words = word_tokenize(phrase)

stemmed_words = []
for word in words:
    stemmed_words.append(stemmer.stem(word))
print(" ".join(stemmed_words))

read reader readili read readabl read


In [19]:
from nltk.stem import WordNetLemmatizer
 
lemmatizer = WordNetLemmatizer()

lemma_words = [lemmatizer.lemmatize(word, pos="v") for word in words]

print(" ".join(lemma_words))

read readers readily read readable readings


# Stopwords Removal

In [20]:
from nltk.corpus import stopwords

stopwords = stopwords.words('english')

phrase = "This is a sample sentence, showing off the stop words filtration."

words = word_tokenize(phrase)

stripped_phrase = []
for word in words:
    if word.lower() not in stopwords:
        stripped_phrase.append(word)
print(" ".join(stripped_phrase))

sample sentence , showing stop words filtration .


# Various Other Techniques
Spell Correction,
Sentiment,
POS tagging

In [21]:
from textblob import TextBlob
phrase = "I havv goood speling"
blob = TextBlob(phrase)

print(blob.correct())

I have good spelling


In [22]:
from textblob import TextBlob
phrase = "what a disgusting book and bad story"
blob = TextBlob(phrase)

print(blob.tags)
print(blob.sentiment)

[('what', 'WP'), ('a', 'DT'), ('disgusting', 'VBG'), ('book', 'NN'), ('and', 'CC'), ('bad', 'JJ'), ('story', 'NN')]
Sentiment(polarity=-0.8499999999999999, subjectivity=0.8333333333333333)


# Transformer Architecture