In [1]:
import torch
import numpy as np

# Initialization 

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

## From NumPy Array

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float64)

In [7]:
x_ones

tensor([[1, 1],
        [1, 1]])

In [8]:
x_rand

tensor([[0.4403, 0.9388],
        [0.7388, 0.2672]], dtype=torch.float64)

## With random or constant values

In [9]:
shape = (2,3)

In [10]:
rand_tensor = torch.rand(shape)

In [11]:
rand_tensor

tensor([[0.2581, 0.1530, 0.6488],
        [0.3998, 0.4929, 0.4949]])

In [12]:
ones_tensor = torch.ones(shape)

In [13]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
zero_tensor = torch.zeros(shape)

In [15]:
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

# Tensor Attributes

In [16]:
tensor = torch.rand(3, 4)

In [17]:
tensor.shape

torch.Size([3, 4])

In [18]:
tensor.dtype

torch.float32

In [19]:
tensor.device

device(type='cpu')

# Tensor Operations

In [20]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(tensor.device)

cuda:0


## Standard numpy-like indexing and slicing

In [21]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

## Dynamic selection 

In [22]:
scores = torch.tensor([[10, 0, 5, 20, 1], [1, 30, 2, 5, 0]])

In [23]:
best_indices = torch.argmax(scores, dim=1)
print(best_indices)

tensor([3, 1])


## Expert selection 

In [24]:
data = torch.tensor([
    [10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33]
])

In [25]:
index_select = torch.tensor([[2], [0], [3]])

In [26]:
select_value = torch.gather(data, dim=1, index=index_select)
print(select_value)

tensor([[12],
        [20],
        [33]])


## Joining tensors

In [27]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

## Multiplying tensors

In [28]:
tensor.mul(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [29]:
tensor*tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [30]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [31]:
tensor @ tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [32]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

## Inplace operations 

In [33]:
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [34]:
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

## Reduction operations

In [35]:
scores = torch.tensor([[10., 20., 30.], [5., 10., 15.]])

In [36]:
average_scores = scores.mean()
print(average_scores)

tensor(15.)


In [37]:
avg_assignment = scores.mean(dim=0)
print(avg_assignment)

tensor([ 7.5000, 15.0000, 22.5000])


In [38]:
avg_student = scores.mean(dim=1)
print(avg_student)

tensor([20., 10.])


# Bridge With NumPy

## Tensor to NumPy array

In [39]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [40]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [41]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## NumPy array to Tensor

In [42]:
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [43]:
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [44]:
np.add(n, 1, out=n)
print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# torch.autograd

In [45]:
from torchvision.models import resnet18, ResNet18_Weights

In [46]:
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [47]:
prediction = model(data)

In [48]:
loss = (prediction - labels).sum()

In [49]:
loss.backward()

In [50]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [51]:
optim.step()

## Differentiation in Autograd

In [52]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [53]:
Q = 3*a**3 - b**2

In [54]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [55]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [56]:
# Pytorch in 1 Hour (Oneshot)
Q.grad_fn

# Exclusion from DAG

In [57]:
x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5, 5), requires_grad=True)

a = x + y
print(f"Does `a` require gradients?: {a.requires_grad}")
b = x + z
print(f"Does `b` require gradients?: {b.requires_grad}")

Does `a` require gradients?: False
Does `b` require gradients?: True


In [58]:
from torch import nn, optim

model = resnet18(weights=ResNet18_Weights.DEFAULT)

# Freeze all the parameters in the network
for param in model.parameters():
    param.requires_grad = False

In [59]:
model.fc = nn.Linear(512, 10)

In [60]:
optimizer = optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

# Neural Networks

In [61]:
import torch.nn
import torch.nn.functional as F

In [62]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)

        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84,10)

    def forward(self, input):
        c1 = F.relu(self.conv1(input))
        s2 = F.max_pool2d(c1, (2, 2))
        c3 = F.relu(self.conv2(s2))
        s4 = F.max_pool2d(c3, 2)

        s4 = torch.flatten(s4, 1)
        f5 = F.relu(self.fc1(s4))
        f6 = F.relu(self.fc2(f5))

        output = self.fc3(f6)
        return output
    
net = Net()
print(net)


Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [63]:
params = list(net.parameters())


In [64]:
len(params)

10

In [65]:
params[0].size()

torch.Size([6, 1, 5, 5])

In [66]:
input = torch.randn(1, 1, 32, 32)

In [67]:
out = net(input)

In [68]:
out

tensor([[ 0.1345,  0.0686,  0.0681,  0.0748, -0.0540, -0.0154,  0.0622, -0.0200,
         -0.0354,  0.0915]], grad_fn=<AddmmBackward0>)

In [69]:
net.zero_grad()

In [70]:
out.backward(torch.randn(1, 10))

## Forward Pass

In [71]:
N = 10
D_in = 1
D_out = 1

In [72]:
X = torch.randn(N, D_in)

In [73]:
true_W =  torch.tensor([[2.0]])
true_b = torch.tensor(1.0)

In [74]:
y_true = X @ true_W + true_b + torch.randn(N, D_out) * 0.1 

In [75]:
W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

In [76]:
print(f"Initial Weight: {W}")
print(f"Initial Bias: {b}")

Initial Weight: tensor([[0.3421]], requires_grad=True)
Initial Bias: tensor([0.1700], requires_grad=True)


In [77]:
y_hat = X @ W + b 

In [78]:
print(f"Shape of our prediction y_hat: {y_hat.shape}\n")
print(f"Prediction y_hat (first 3 rows):\n {y_hat[:3]}\n")
print(f"True Labels y_true (first 3 rows):\n {y_true[:3]}")

Shape of our prediction y_hat: torch.Size([10, 1])

Prediction y_hat (first 3 rows):
 tensor([[0.2065],
        [0.3617],
        [0.1950]], grad_fn=<SliceBackward0>)

True Labels y_true (first 3 rows):
 tensor([[1.1338],
        [2.1081],
        [1.2214]])


In [79]:
error = y_hat - y_true

In [80]:
squared_error = error ** 2

In [81]:
loss = squared_error.mean()
print(loss)

tensor(1.7312, grad_fn=<MeanBackward0>)


In [82]:
loss.backward()

In [83]:
W.grad

tensor([[-1.1976]])

In [84]:
b.grad

tensor([-1.6757])

In [85]:
# Hyperparameters
learning_rate, epochs = 0.01, 100

In [86]:
# Reinitailize Parameters
W, b = torch.randn(1, 1, requires_grad=True), torch.randn(1, requires_grad=True)

In [87]:
for epoch in range(epochs):
    # Forward Pass And Loss
    y_hat = X @ W + b 
    loss = torch.mean((y_hat- y_true)**2)

    # Backward Loss
    loss.backward()

    # Update Parameters
    with torch.no_grad():
        W -= learning_rate * W.grad
        b -= learning_rate * b.grad

    # Zero Gradients
    W.grad.zero_()
    b.grad.zero_()

    if epoch % 10 == 0:
        print(f'Epoch {epoch:02d}: Loss={loss.item():.4f}, W={W.item():.3f}, b={b.item():.3f}')

print(f"\nFinal Parameters: W={W.item():.3f}, b={b.item():.3f}")
print(f"True Parameters: W=2.000, b=1.000")

Epoch 00: Loss=5.4114, W=-0.140, b=-0.874
Epoch 10: Loss=3.9511, W=0.010, b=-0.529
Epoch 20: Loss=2.9334, W=0.150, b=-0.247
Epoch 30: Loss=2.2167, W=0.279, b=-0.018
Epoch 40: Loss=1.7057, W=0.400, b=0.170
Epoch 50: Loss=1.3362, W=0.512, b=0.323
Epoch 60: Loss=1.0647, W=0.616, b=0.448
Epoch 70: Loss=0.8619, W=0.714, b=0.550
Epoch 80: Loss=0.7077, W=0.804, b=0.633
Epoch 90: Loss=0.5883, W=0.889, b=0.700

Final Parameters: W=0.960, b=0.750
True Parameters: W=2.000, b=1.000


## NN.Linear

In [88]:
D_in = 1
D_out = 1

In [89]:
linear_layer = torch.nn.Linear(in_features=D_in, out_features=D_out)

In [90]:
linear_layer.weight

Parameter containing:
tensor([[-0.1207]], requires_grad=True)

In [91]:
linear_layer.bias

Parameter containing:
tensor([0.6362], requires_grad=True)

In [92]:
y_hat_nn = linear_layer(X)

In [93]:
y_hat_nn[:3]

tensor([[0.6233],
        [0.5686],
        [0.6274]], grad_fn=<SliceBackward0>)

## Activation Function 

### RELU

In [94]:
relu = torch.nn.ReLU()

In [95]:
sample_data = torch.tensor([-2.0, -0.5, 0.0, 0.5, 2.0])
activated_data = relu(sample_data)

In [96]:
activated_data

tensor([0.0000, 0.0000, 0.0000, 0.5000, 2.0000])

### GELU

In [97]:
gelu = torch.nn.GELU()

In [98]:
activated_data = gelu(sample_data)

In [99]:
activated_data

tensor([-0.0455, -0.1543,  0.0000,  0.3457,  1.9545])

### SoftMax

In [100]:
softmax = torch.nn.Softmax()

In [101]:
activated_data = softmax(sample_data)

c:\Users\iamha\anaconda3\envs\tf-jupyter\lib\site-packages\torch\nn\modules\module.py:1773: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [102]:
activated_data

tensor([0.0126, 0.0563, 0.0928, 0.1529, 0.6855])

## NN.Embedding

In [103]:
vocab_size = 10
embedding_dim = 3

In [104]:
embedding_layer = torch.nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

In [105]:
input_ids = torch.tensor([[1, 5, 0, 8]])
word_vectors = embedding_layer(input_ids)

## LayerNorm

In [106]:
norm_layer = torch.nn.LayerNorm(normalized_shape=3)

In [107]:
input_features = torch.tensor([[[1.0, 2.0 ,3.0], [4.0, 5.0, 6.0]]])

In [108]:
normalized_features = norm_layer(input_features)

In [109]:
normalized_features.mean(dim=-1)

tensor([[0., 0.]], grad_fn=<MeanBackward1>)

In [110]:
normalized_features.std(dim=-1)

tensor([[1.2247, 1.2247]], grad_fn=<StdBackward0>)

## NN.DropOut

In [111]:
dropout_layer = torch.nn.Dropout(p=0.5)

In [112]:
input_tensor = torch.ones(1, 10)


In [113]:
dropout_layer.train()

Dropout(p=0.5, inplace=False)

In [114]:
output_during_train = dropout_layer(input_tensor)
print(output_during_train)

tensor([[0., 2., 2., 2., 0., 0., 0., 0., 0., 0.]])


In [115]:
dropout_layer.eval()

Dropout(p=0.5, inplace=False)

In [116]:
output_during_eval = dropout_layer(input_tensor)
print(output_during_eval)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [117]:
import torch.nn as nn

class LinearRegressionModel(nn.Module):
    def __init__(self, in_feautres, out_features):
        super().__init__()
        self.linear_layer = nn.Linear(in_features=in_feautres, out_features=out_features)

    def forward(self, x):
        return self.linear_layer(x)
    
model = LinearRegressionModel(in_feautres=1, out_features=1)

In [118]:
model

LinearRegressionModel(
  (linear_layer): Linear(in_features=1, out_features=1, bias=True)
)

In [119]:
import torch.optim as optim

learning_rate = 0.01

optimizer = optim.Adam(model.parameters(), lr=learning_rate)

loss_fn = nn.MSELoss()

In [ ]:
epochs = 100
for epoch in range(epochs):
    # Forward Pass
    y_hat = model(X)

    # Loss Calculation 
    loss = loss_fn(y_hat, y_true)

    # The 3-Line Mantra  
    # Zero the gradients 
    optimizer.zero_grad()
    # Compute gradients 
    loss.backward()
    # Update the parameters 
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch:0.2d}: Loss={loss.item():.4f}")